/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Sio4MenuInterface } from "./components/sio4-menu";
import { Sio4MenuItemInterface } from "./components/sio4-menu-item";
export namespace Components {
    interface Sio4App {
        "color": string | undefined;
        "menu": Sio4MenuInterface | undefined;
        "sidemenu": 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'none';
        "title": string;
    }
    interface Sio4Icon {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface Sio4Menu {
        "color": string | undefined;
        "enabled": boolean;
        "label": string;
        "layout": 'flat' | 'accordion';
        "lines": 'full' | 'inset' | 'none';
        "menuId": string;
        "menuItems": Sio4MenuItemInterface[] | undefined;
        "position": 'top' | 'bottom' | 'hover';
        "toggleIcon": string;
        "toggleIconSlot": 'start' | 'end';
    }
    interface Sio4MenuItem {
        "badge": number;
        "caption": string | undefined;
        "disabled": boolean;
        "icon": string | undefined;
        "layout": string;
        "menuItemId": number | undefined;
        /**
          * The mode determines which platform styles to use.
         */
        "mode"?: "ios" | "md";
        "styleMenu": string;
        "tabbed": boolean;
        "type": 'download' | 'navigate';
        "url": string;
    }
}
declare global {
    interface HTMLSio4AppElement extends Components.Sio4App, HTMLStencilElement {
    }
    var HTMLSio4AppElement: {
        prototype: HTMLSio4AppElement;
        new (): HTMLSio4AppElement;
    };
    interface HTMLSio4IconElement extends Components.Sio4Icon, HTMLStencilElement {
    }
    var HTMLSio4IconElement: {
        prototype: HTMLSio4IconElement;
        new (): HTMLSio4IconElement;
    };
    interface HTMLSio4MenuElement extends Components.Sio4Menu, HTMLStencilElement {
    }
    var HTMLSio4MenuElement: {
        prototype: HTMLSio4MenuElement;
        new (): HTMLSio4MenuElement;
    };
    interface HTMLSio4MenuItemElement extends Components.Sio4MenuItem, HTMLStencilElement {
    }
    var HTMLSio4MenuItemElement: {
        prototype: HTMLSio4MenuItemElement;
        new (): HTMLSio4MenuItemElement;
    };
    interface HTMLElementTagNameMap {
        "sio4-app": HTMLSio4AppElement;
        "sio4-icon": HTMLSio4IconElement;
        "sio4-menu": HTMLSio4MenuElement;
        "sio4-menu-item": HTMLSio4MenuItemElement;
    }
}
declare namespace LocalJSX {
    interface Sio4App {
        "color"?: string | undefined;
        "menu"?: Sio4MenuInterface | undefined;
        "sidemenu"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'none';
        "title"?: string;
    }
    interface Sio4Icon {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface Sio4Menu {
        "color"?: string | undefined;
        "enabled"?: boolean;
        "label"?: string;
        "layout"?: 'flat' | 'accordion';
        "lines"?: 'full' | 'inset' | 'none';
        "menuId"?: string;
        "menuItems"?: Sio4MenuItemInterface[] | undefined;
        "position"?: 'top' | 'bottom' | 'hover';
        "toggleIcon"?: string;
        "toggleIconSlot"?: 'start' | 'end';
    }
    interface Sio4MenuItem {
        "badge"?: number;
        "caption"?: string | undefined;
        "disabled"?: boolean;
        "icon"?: string | undefined;
        "layout"?: string;
        "menuItemId"?: number | undefined;
        /**
          * The mode determines which platform styles to use.
         */
        "mode"?: "ios" | "md";
        "styleMenu"?: string;
        "tabbed"?: boolean;
        "type"?: 'download' | 'navigate';
        "url"?: string;
    }
    interface IntrinsicElements {
        "sio4-app": Sio4App;
        "sio4-icon": Sio4Icon;
        "sio4-menu": Sio4Menu;
        "sio4-menu-item": Sio4MenuItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sio4-app": LocalJSX.Sio4App & JSXBase.HTMLAttributes<HTMLSio4AppElement>;
            "sio4-icon": LocalJSX.Sio4Icon & JSXBase.HTMLAttributes<HTMLSio4IconElement>;
            "sio4-menu": LocalJSX.Sio4Menu & JSXBase.HTMLAttributes<HTMLSio4MenuElement>;
            "sio4-menu-item": LocalJSX.Sio4MenuItem & JSXBase.HTMLAttributes<HTMLSio4MenuItemElement>;
        }
    }
}
